# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Continuous Integration

on:
  push:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate with Google Cloud using Workload Identity Federation
      uses: google-github-actions/auth@v2
      with:
        project_id: "${{ env.PROJECT_ID }}"
        workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
        service_account: "${{ env.SERVICE_ACCOUNT }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest google-cloud-bigquery
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    if: ${{ always() }}
    needs: lint

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate with Google Cloud using Workload Identity Federation
      uses: google-github-actions/auth@v2
      with:
        project_id: "${{ env.PROJECT_ID }}"
        workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
        service_account: "${{ env.SERVICE_ACCOUNT }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest google-cloud-bigquery
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest
