name: Python Continuous Integration

on:
  push:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    if: ${{ always() }}
    needs: lint

    steps:
    - uses: actions/checkout@v4
    
    # Use the same authentication method as Cloud Run (Workload Identity Federation)
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: "${{ secrets.GCP_PROJECT_ID }}"  # Your project ID in secrets
        workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"  # The workload identity provider
        service_account: "${{ secrets.SERVICE_ACCOUNT }}"  # The service account used for the workload identity

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest
